apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: {{ .Values.replicaCount }}

  
  strategy:
    type: RollingUpdate
  

  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp
        azure.workload.identity/use: "true"

    spec:
      
      serviceAccountName: myapp-sa


      # nodeSelector / tolerations belong here (NOT inside volumeAttributes)
      nodeSelector:
        kubernetes.io/os: linux
        agentpool: nodepool1

      tolerations:
        - operator: Exists

      volumes:
        - name: kv-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: akv-secrets   # ONLY valid entry

      containers:
        - name: myapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3

          volumeMounts:
            - name: kv-secrets
              mountPath: "/mnt/secrets"
              readOnly: true