image:
  repository: starterkitacr.azurecr.io/myapp
  tag: v1
  pullPolicy: IfNotPresent
  
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: false
  className: ""
  hosts:
    - host: myapp.example.com
      paths:
        - path: /
          pathType: Prefix
resources: {}
replicaCount: 1

azure:
  tenantID: "ec7789f0-7ef2-4ff6-89b1-a74d3fc8f81c"
  keyVaultName: "sk-dev2-kv2"
workloadIdentity:
  clientId: "b876042f-874e-44ab-b0ac-697c2260f98e"