image:
  repository: starterkitacr.azurecr.io/myapp
  tag: v1
  pullPolicy: IfNotPresent
  
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: false
  className: ""
  hosts:
    - host: myapp.example.com
      paths:
        - path: /
          pathType: Prefix
resources: {}
replicaCount: 1

azure:
  clientID: ""
  tenantID: ""
  keyVaultName: ""
workloadIdentity:
  clientId: "341c8ac0-d6be-43c0-943d-05a98f5e5099"