apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    clientID: b876042f-874e-44ab-b0ac-697c2260f98e
    tenantId: ec7789f0-7ef2-4ff6-89b1-a74d3fc8f81c
    keyvaultName: skdev2kv
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    objects: |
      array:
        - |
          objectName: app-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: app-key
          objectType: secret
          objectVersion: ""