apiVersion: secrets-store.csi.k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-secrets
  namespace: starterkit
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "KV_NAME_TO_FILL"
    tenantId: "TENANT_ID_TO_FILL"
    objects: |
      array:
        - |
          objectName: acr-sp-app-id
          objectType: secret
        - |
          objectName: acr-sp-secret
          objectType: secret
  secretObjects: []
