[docker_server]
94.245.88.190 ansible_user=vinadmin ansible_ssh_private_key_file=~/.ssh/id_ed25519

[jenkins]
52.236.64.255 ansible_user=vinadmin ansible_ssh_private_key_file=~/.ssh/id_ed25519

[all:vars]
ansible_python_interpreter=/usr/bin/python3
