[docker_server]
52.138.253.11 ansible_user=vinadmin ansible_ssh_private_key_file=~/.ssh/id_ed25519

[jenkins]
20.123.11.197 ansible_user=vinadmin ansible_ssh_private_key_file=~/.ssh/id_ed25519

[all:vars]
ansible_python_interpreter=/usr/bin/python3
