[docker_server]
98.71.70.171 ansible_user=vinadmin ansible_ssh_private_key_file=~/.ssh/id_ed25519

[jenkins]
20.123.30.78 ansible_user=vinadmin ansible_ssh_private_key_file=~/.ssh/id_ed25519

[all:vars]
ansible_python_interpreter=/usr/bin/python3
