# ansible/roles/jcasc/tasks/main.yml
---

- name: Ensure Jenkins JCasC directory exists
  file:
    path: /var/lib/jenkins/casc_configs
    state: directory
    owner: jenkins
    group: jenkins
    mode: "0755"
  become: true


- name: Deploy Jenkins Configuration as Code file
  copy:
    src: jenkins.yaml
    dest: /var/lib/jenkins/casc_configs/jenkins.yaml
    owner: jenkins
    group: jenkins
    mode: "0644"
  become: true

- name: Install Jenkins Plugin CLI
  apt:
    name: jenkins-plugin-cli
    state: present
    update_cache: yes
  become: true

- name: Download Jenkins Plugin CLI JAR
  get_url:
    url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/latest/download/jenkins-plugin-manager.jar
    dest: /usr/local/lib/jenkins-plugin-manager.jar
    mode: "0755"
  become: true

- name: Install Jenkins plugins from plugins.txt (APT Jenkins)
  command: >
    java -jar /usr/local/lib/jenkins-plugin-manager.jar
    --plugin-file {{ role_path }}/files/plugins.txt
    --plugin-dir /var/lib/jenkins/plugins
    --verbose
  become: true
  environment:
    JENKINS_HOME: /var/lib/jenkins


# THIS IS THE MISSING PIECE
- name: Ensure systemd drop-in directory for Jenkins exists
  file:
    path: /etc/systemd/system/jenkins.service.d
    state: directory
    mode: "0755"
  become: true


- name: Configure Jenkins environment variables for JCasC and GitHub
  copy:
    dest: /etc/systemd/system/jenkins.service.d/jcasc-env.conf
    content: |
      [Service]
      Environment="CASC_JENKINS_CONFIG=/var/lib/jenkins/casc_configs/jenkins.yaml"
      Environment="GITHUB_USERNAME={{ github_username }}"
      Environment="GITHUB_TOKEN={{ github_token }}"
  become: true


- name: Reload systemd and restart Jenkins
  systemd:
    daemon_reload: true
    name: jenkins
    state: restarted
  become: true